# Generated by Django 3.2.7 on 2021-09-26 07:38

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(re.compile('(\\+2)?([0-9]{11})$'), 'wallet phone number must be 11 digits')])),
                ('balance', models.FloatField(default=0.0)),
                ('password', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(re.compile('([0-9]{6})$'), 'wallet password must be 6 numbers')])),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
